# Generated by Django 3.2.18 on 2023-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('no_days', models.IntegerField()),
                ('nails', models.BooleanField(default=False)),
                ('teeth', models.BooleanField(default=False)),
                ('bath', models.BooleanField(default=False)),
                ('hair_cuts', models.BooleanField(default=False)),
                ('pickup', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
