# Generated by Django 3.2.18 on 2023-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=80)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (3, 'Rejected')], default=0)),
                ('package', models.CharField(choices=[(None, 'Pick a choice'), ('Iron', 'Iron Package'), ('Bronze', 'Bronze Package'), ('Silver', 'Silver Package'), ('Gold', 'Gold Package')], default=None, max_length=10)),
                ('breed', models.CharField(default='', max_length=200)),
                ('weight', models.CharField(choices=[(None, 'Pick a choice'), ('Mini', 'Mini (< 2 kg)'), ('Small', 'Small (2-8 kg)'), ('Medium', 'Medium (8-15 kg)'), ('Large', 'Large (> 15 kg)')], default=None, max_length=10)),
                ('height', models.CharField(choices=[(None, 'Pick a choice'), ('Mini', 'Mini (< 25 cm)'), ('Small', 'Small (25-36 cm)'), ('Medium', 'Medium (36-45 cm)'), ('Large', 'Large (> 45 cm)')], default=None, max_length=10)),
                ('gender', models.CharField(choices=[(None, 'Pick a choice'), ('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10)),
                ('neutered', models.BooleanField(default=False)),
                ('insured', models.BooleanField(default=False)),
                ('vaccinated', models.BooleanField(default=False)),
                ('experience', models.BooleanField(default=False)),
                ('info', models.TextField(blank=True)),
                ('owner_first_name', models.CharField(max_length=200)),
                ('owner_last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('no_days', models.IntegerField()),
                ('nails', models.BooleanField(default=False)),
                ('teeth', models.BooleanField(default=False)),
                ('bath', models.BooleanField(default=False)),
                ('hair_cuts', models.BooleanField(default=False)),
                ('pickup', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
