# Generated by Django 3.2.18 on 2023-03-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=200, unique=True)),
                ('breed', models.CharField(max_length=200, unique=True)),
                ('weight', models.CharField(choices=[(None, 'Pick a choice'), ('Mini', 'Mini (< 2 kg)'), ('Small', 'Small (2-8 kg)'), ('Medium', 'Medium (8-15 kg)'), ('Large', 'Large (> 15 kg)')], default=None, max_length=10)),
                ('height', models.CharField(choices=[(None, 'Pick a choice'), ('Mini', 'Mini (< 25 cm)'), ('Small', 'Small (25-36 cm)'), ('Medium', 'Medium (36-45 cm)'), ('Large', 'Large (> 45 cm)')], default=None, max_length=10)),
            ],
        ),
    ]
