# Generated by Django 3.2.18 on 2023-03-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='slug',
        ),
    ]
