# Generated by Django 3.2.18 on 2023-03-21 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daycare', '0002_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='application',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[(None, 'Pick a choice'), ('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='info',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='neutered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='owner_first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='owner_last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (3, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='breed',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='dog_name',
            field=models.CharField(max_length=200),
        ),
    ]
