# Generated by Django 3.2.18 on 2023-03-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
