# Generated by Django 3.2.18 on 2023-03-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0003_alter_application_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='author',
            field=models.CharField(max_length=80),
        ),
    ]
