# Generated by Django 3.2.18 on 2023-03-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0004_application_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='slug',
        ),
    ]
